swagger: '2.0'
info:
  title: Redadalertas API
  description: API Documentation of REST API for Redadalertas
  version: '1.0.0'
host: api.redadalertas.com
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /session:
    post:
      summary: Creates a new session, logging the user in
      description: Accepts a username and password, return an accessToken
      consumes:
        - application/json
      produces:
        - applications/json
      parameters:
        -
          name: userLogin
          in: body
          description: Object with user login details
          required: true
          schema:
            $ref: '#/definitions/UserLogin'
      responses:
        201:
          description: A new session was created. Returns an accessToken
          schema:
            $ref: '#/definitions/Session'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Deletes a session, loggin the user out.
      description: This will return nothing
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        -
          name: accessToken
          description: The accessToken received on login
          in: body
          required: true
          schema:
            $ref: '#/definitions/AccessToken'
      responses:
        200:
          description: Successfully logged user out, deleting user session
        400:
          description: Server error.
          schema:
            $ref: '#/definitions/Error'
definitions:
  UserLogin:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  Session:
    type: object
    properties:
      accessToken:
        type: string
  AccessToken:
    type: string
  Error:
    type: object
    properties:
      message:
        type: string
