swagger: '2.0'
info:
  title: Redadalertas API
  description: API Documentation of REST API for Redadalertas
  version: '1.0.0'
host: example.com
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /session:
    post:
      summary: Creates a new session
      consumes:
        - application/json
      produces:
        - applications/json
      parameters:
        -
          name: userLogin
          in: body
          description: Object with user login details
          required: true
          schema:
            $ref: '#/definitions/userLogin'
      responses:
        201:
          description: A new session was created. Returns an accessToken
          schema:
            $ref: '#/definitions/Session'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/Error'
definitions:
  userLogin:
    type: object
    properties:
      phoneNumber:
        type: string
      password:
        type: string
  Session:
    type: object
    properties:
      accessToken:
        type: string
  Error:
    type: object
    properties:
      message:
        type: string
